export function projectPage(): string {
  return `<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>GitFlare — Project</title><meta name="description" content="GitFlare — Your code. Your agents. Your platform. Build and review software with AI agents."><meta name="application-name" content="GitFlare"><meta property="og:site_name" content="GitFlare"><meta property="og:title" content="GitFlare"><meta property="og:description" content="Your code. Your agents. Your platform."><meta name="twitter:card" content="summary"><meta name="twitter:title" content="GitFlare"><meta name="twitter:description" content="Your code. Your agents. Your platform.">
<style>
body{font-family:ui-sans-serif,system-ui;background:#0b0d10;color:#f5f7fa;margin:0}main{max-width:1050px;margin:auto;padding:32px 20px}
.brand{color:#8b9cff;font-weight:800}.muted{color:#8e98a8}.tabs{display:flex;gap:8px;margin:24px 0;border-bottom:1px solid #293041}
.tab{padding:10px 12px;cursor:pointer;color:#9ca3af}.tab.active{color:#fff;border-bottom:2px solid #8b9cff}.panel{background:#151922;border:1px solid #293041;border-radius:16px;padding:20px}
.file{display:flex;justify-content:space-between;padding:11px 8px;border-bottom:1px solid #242b38;cursor:pointer}.file:hover{background:#1a1f29}
.code{white-space:pre-wrap;background:#0d1117;padding:16px;border-radius:10px;overflow:auto;font:12px ui-monospace,monospace}.hidden{display:none}
button{background:#252b36;color:#fff;border:0;border-radius:8px;padding:9px 12px;cursor:pointer}.filetabs{display:flex;gap:8px;margin:12px 0}
.explain{line-height:1.65;background:#10141b;padding:16px;border-radius:10px}a{color:#aeb9ff}
</style></head><body><main>
<div class="brand">GitFlare</div><p class="muted">Your code. Your agents. Your platform.</p><h1 id="name">Your project</h1><p class="muted">Your code lives here. GitFlare keeps the history for you.</p>
<div class="tabs"><div class="tab active" data-tab="overview">Overview</div><div class="tab" data-tab="files">Files</div><div class="tab" data-tab="updates">Updates</div><div class="tab" data-tab="build">Build</div><div class="tab" data-tab="deploy">Deploy</div></div>
<section id="overview" class="panel"><h2>Project overview</h2><p>This is the current version of your project. Browse what is inside, see previous updates, or tell GitFlare what you want to build next.</p><div id="summary" class="explain">Understanding your project…</div><p><button id="browse">Browse project files</button></p><details style="margin-top:20px"><summary>Developer details</summary><div id="developer" class="code" style="margin-top:10px">Loading…</div><p><button id="gitAccess">Get temporary Git access</button></p><div id="gitCredentials" class="code hidden"></div></details></section>
<section id="files" class="panel hidden"><h2>Files</h2><p class="muted">These are the files that make up your project.</p><div id="fileList">Loading…</div>
<div id="viewer" class="hidden"><p><button id="backFiles">← Back to files</button></p><h3 id="fileName"></h3><div class="filetabs"><button id="understandTab">Understand</button><button id="codeTab">Code</button></div><div id="explanation" class="explain">Understanding this file…</div><pre class="code hidden" id="fileContent"></pre></div></section>
<section id="updates" class="panel hidden"><h2>Updates</h2><p class="muted">A history of changes made to your project.</p><div id="history">Loading…</div></section><section id="build" class="panel hidden"><h2>What would you like to change?</h2><p class="muted">Describe the outcome in your own words. GitFlare will figure out the technical work.</p><textarea id="buildRequest" style="width:100%;min-height:120px;box-sizing:border-box;background:#0d1117;color:#fff;border:1px solid #303848;border-radius:10px;padding:12px" placeholder="For example: Add dark mode and let people choose it in Settings."></textarea><p><button id="startUpdate">Start update</button></p><div id="progress" class="hidden" style="margin-top:16px"><div class="muted" style="margin-bottom:8px">Your update</div><div id="steps"></div></div><div class="muted" id="buildStatus"></div><div id="clarifyBuild" class="hidden" style="margin-top:14px"><textarea id="clarifyText" style="width:100%;min-height:80px;box-sizing:border-box;background:#0d1117;color:#fff;border:1px solid #303848;border-radius:10px;padding:12px" placeholder="Add a little more detail…"></textarea><p><button id="continueBuild">Continue</button></p></div></section><section id="deploy" class="panel hidden"><h2>Deploy your project</h2><p class="muted">Put the approved version of your project online.</p><div class="file"><span><strong>Cloudflare</strong><br><span class="muted">Available for compatible Worker projects</span></span><button id="deployCloudflare">Deploy</button></div><div class="file"><span><strong>Vercel</strong><br><span class="muted">Future provider</span></span><span class="muted">Coming later</span></div><div class="file"><span><strong>Railway</strong><br><span class="muted">Future provider</span></span><span class="muted">Coming later</span></div><div id="deployStatus" class="muted" style="margin-top:14px"></div><h3>Deployment history</h3><div id="deployments">Loading…</div></section>
</main><script>
const projectId=new URLSearchParams(location.search).get('id');loadProjectInfo();
let currentPath='',treeStack=[];
function show(id){document.querySelectorAll('section.panel').forEach(x=>x.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));if(id==='files')loadFiles();if(id==='updates')loadHistory();if(id==='deploy')loadDeployments()}
document.querySelectorAll('.tab[data-tab]').forEach(x=>x.onclick=()=>show(x.dataset.tab));loadOverview();loadDeveloper();document.getElementById('startUpdate').onclick=startUpdate;document.getElementById('gitAccess').onclick=getGitAccess;document.getElementById('browse').onclick=()=>show('files');
async function getGitAccess(){const box=document.getElementById('gitCredentials');box.classList.remove('hidden');box.textContent='Creating temporary credential…';const d=await fetch('/api/project/token',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId})}).then(r=>r.json());box.textContent=d.ok?'Git remote: '+d.remote+'\nTemporary token (expires in 1 hour): '+d.token+'\n\nKeep this private. GitFlare does not show it again after you leave this page.':(d.error||'Git access is unavailable.')}
async function loadDeveloper(){if(!projectId)return;try{const d=await fetch('/api/project/developer?projectId='+encodeURIComponent(projectId)).then(r=>r.json());if(!d.ok){developer.textContent='Developer details unavailable.';return}developer.textContent='Git hosting: '+(d.repository.remoteConfigured?'Ready':'Unavailable')+'\n\nRecent Git history:\n'+(d.history||[]).map(x=>String(x.hash||'').slice(0,7)+'  '+(x.message||'Update')).join('\n')}catch{developer.textContent='Developer details unavailable.'}}
async function loadProjectInfo(){if(!projectId)return;try{const d=await fetch('/api/project/info?projectId='+encodeURIComponent(projectId)).then(r=>r.json());if(d.ok){document.getElementById('name').textContent=d.project.name;document.title=d.project.name+' — GitFlare'}}catch{document.getElementById('name').textContent='Your project'}}
async function loadOverview(){if(!projectId){summary.textContent='Open a project to see its overview.';return}try{const d=await fetch('/api/projects/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId})}).then(r=>r.json());summary.textContent=d.ok?'GitFlare recognizes this as a '+d.projectType+' with '+d.fileCount+' files. Your project is stored here with version history, so you can understand it, update it, and recover earlier changes.':'Your project is stored here with version history.'}catch{summary.textContent='Your project is stored here with version history.'}}
async function loadFiles(treeHash,path){if(!projectId){fileList.textContent='No project selected.';return}const d=await fetch('/api/project/files?projectId='+encodeURIComponent(projectId)+(treeHash?'&tree='+encodeURIComponent(treeHash):'')).then(r=>r.json());currentPath=path||'';let h=currentPath?'<div class="file" id="up"><span>← Back</span><span class="muted">'+currentPath+'</span></div>':'';h+=(d.files||[]).map(x=>'<div class="file entry" data-name="'+encodeURIComponent(x.name||x.path||'')+'" data-path="'+encodeURIComponent((currentPath?currentPath+'/':'')+(x.name||x.path||''))+'" data-hash="'+encodeURIComponent(x.hash||'')+'" data-tree="'+(x.type==='tree'?'1':'0')+'"><span>'+(x.type==='tree'?'📁 ':'📄 ')+(x.name||x.path||'')+'</span><span class="muted">'+(x.type==='tree'?'Folder':'File')+'</span></div>').join('');fileList.innerHTML=h||'This project does not have files yet.';if(document.getElementById('up'))document.getElementById('up').onclick=goUp;document.querySelectorAll('.entry').forEach(el=>el.onclick=()=>{if(el.dataset.tree==='1'){treeStack.push({hash:d.treeHash,path:currentPath});loadFiles(decodeURIComponent(el.dataset.hash),decodeURIComponent(el.dataset.path))}else openFile(decodeURIComponent(el.dataset.path))})}
function goUp(){const p=treeStack.pop();p?loadFiles(p.hash,p.path):loadFiles()}
async function openFile(path){const d=await fetch('/api/project/file?projectId='+encodeURIComponent(projectId)+'&path='+encodeURIComponent(path)).then(r=>r.json());fileList.classList.add('hidden');viewer.classList.remove('hidden');fileName.textContent=path;fileContent.textContent=d.binary?'This file cannot be previewed as text.':(d.content||'');fileMode('understand');explanation.textContent=d.binary?'This file is not plain text, so GitFlare cannot explain its contents yet.':'Understanding this file…';if(!d.binary){const x=await fetch('/api/project/explain-file',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId,path})}).then(r=>r.json());explanation.textContent=x.explanation||'GitFlare could not explain this file yet.'}}
function fileMode(mode){explanation.classList.toggle('hidden',mode!=='understand');fileContent.classList.toggle('hidden',mode!=='code')}
understandTab.onclick=()=>fileMode('understand');codeTab.onclick=()=>fileMode('code');backFiles.onclick=()=>{viewer.classList.add('hidden');fileList.classList.remove('hidden')};
const buildSteps=['Understanding your request','Planning the work','Building the parts','Checking safety','Combining the work','Running project checks','Ready for review'];
function setProgress(active){progress.classList.remove('hidden');steps.innerHTML=buildSteps.map((x,i)=>'<div style="padding:6px 0">'+(i<active?'✓ ':i===active?'● ':'○ ')+x+'</div>').join('')}
async function executePlanned(m,p,objective,ids){setProgress(2);buildStatus.textContent='Building the different parts…';const attempts=m.attempts.map((a,i)=>({id:a.id,agentId:a.agentId,repositoryName:a.repository.name,objective:p.plan?.tasks?.[i]?.objective||objective}));const x=await fetch('/api/missions/execute',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({missionId:m.id,objective,attempts})}).then(r=>r.json());if(!x.results){buildStatus.textContent=x.error||'The update could not be completed.';return}setProgress(x.integration?.ready?6:4);buildStatus.textContent=x.integration?.ready?'Your update is ready for review.':'GitFlare finished building, but a final check needs attention.';setTimeout(()=>location.href='/mission-review?missionId='+encodeURIComponent(m.id),650)}
async function startUpdate(){const objective=buildRequest.value.trim();if(!objective){buildStatus.textContent='Tell GitFlare what you want to change.';return}setProgress(0);buildStatus.textContent='Understanding your request…';const ids=['agent-a','agent-b','agent-c','agent-d'];const m=await fetch('/api/missions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId,title:'Project update',objective,agentIds:ids})}).then(r=>r.json());if(!m.id){buildStatus.textContent=m.error||'Could not start the update.';return}setProgress(1);buildStatus.textContent='Making a plan…';const p=await fetch('/api/missions/plan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({missionId:m.id,objective,agentIds:ids})}).then(r=>r.json());if(p.requiresClarification){buildStatus.textContent=p.message||'GitFlare needs a little more detail.';clarifyBuild.classList.remove('hidden');window.pendingBuild={m,objective,ids};return}await executePlanned(m,p,objective,ids)}
async function continueBuildFlow(){const pending=window.pendingBuild;const extra=clarifyText.value.trim();if(!pending||!extra)return;clarifyBuild.classList.add('hidden');const objective=pending.objective+'\nAdditional detail from the user: '+extra;buildStatus.textContent='Thanks. Updating the plan…';setProgress(1);const p=await fetch('/api/missions/plan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({missionId:pending.m.id,objective,agentIds:pending.ids})}).then(r=>r.json());if(p.requiresClarification){pending.objective=objective;clarifyBuild.classList.remove('hidden');buildStatus.textContent=p.message||'GitFlare still needs a little more detail.';return}window.pendingBuild=null;await executePlanned(pending.m,p,objective,pending.ids)}
document.getElementById('continueBuild').onclick=continueBuildFlow;document.getElementById('deployCloudflare').onclick=deployCloudflare;
async function deployCloudflare(){deployStatus.textContent='Deploying the approved version to Cloudflare…';const r=await fetch('/api/project/deploy',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId,provider:'cloudflare'})});const d=await r.json();if(r.ok){deployStatus.innerHTML='✓ Live on Cloudflare'+(d.url?' · <a href="'+d.url+'" target="_blank" rel="noopener">Open live project</a>':'');loadDeployments()}else deployStatus.textContent=d.error||'Deployment failed.'}
async function loadDeployments(){if(!projectId)return;const d=await fetch('/api/project/deployments?projectId='+encodeURIComponent(projectId)).then(r=>r.json());deployments.innerHTML=(d.deployments||[]).map(x=>'<div class="file"><span>'+x.provider+' · '+x.status+'</span><span>'+(x.live_url?'<a href="'+x.live_url+'" target="_blank" rel="noopener">Open</a>':'')+'</span></div>').join('')||'<span class="muted">No deployments yet.</span>'}
async function loadHistory(){if(!projectId){history.textContent='No project selected.';return}const d=await fetch('/api/project/updates?projectId='+encodeURIComponent(projectId)).then(r=>r.json());history.innerHTML=(d.updates||[]).map(x=>'<div style="padding:14px 8px;border-bottom:1px solid #242b38"><strong>'+(x.title||'Project update')+'</strong><div style="margin-top:5px">'+(x.objective||'')+'</div><div class="muted" style="margin-top:6px">'+(x.status==='applied'?'✓ Added to your project':x.status==='planning'?'In progress':x.status)+'</div></div>').join('')||'No updates yet.'}
</script></body></html>`;
}
